sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
      env:
        - EXECUTE_COVERAGE=true
    - php: hhvm

before_install:
    - composer self-update
    - composer --version
    - hhvm --version

install:
    - COMPOSER_ROOT_VERSION=dev-master composer update --prefer-source

script:
  - hhvm bin/phpunit --version
  - hhvm tests/xmlsec-decrypt.phpt && echo ok
  - hhvm tests/xmlsec-decrypt-content.phpt && echo ok
  - hhvm xmlsec-encrypt.phpt
  - if [[ "$TRAVIS_PHP_VERSION" == "hhvm" ]]; then hhvm vendor/phpunit/phpunit/phpunit -v --debug tests; fi
  - if [[ $EXECUTE_COVERAGE == 'true' && "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then bin/phpunit -v --debug --coverage-clover clover.xml tests; fi
  - if [[ $EXECUTE_COVERAGE != 'true' && "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then bin/phpunit -v --debug tests; fi
  - echo done

after_success:
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then bash <(curl -s https://codecov.io/bash); fi
