sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env:
        - EXECUTE_COVERAGE=true
    - php: 7
    - php: hhvm

before_install:
    - composer self-update
    - composer --version
    - hhvm --version

install:
    - COMPOSER_ROOT_VERSION=dev-master composer update --prefer-source

script:
  - bin/phpunit --version
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then bin/phpunit -v --debug --coverage-clover clover.xml tests; fi
  - if [[ $EXECUTE_COVERAGE != 'true' ]]; then bin/phpunit -v --debug tests; fi
  - echo done

after_success:
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then bash <(curl -s https://codecov.io/bash); fi
